apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-servicemonitor
  namespace: {{ .Values.common.namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - todoapp
  selector:
    matchLabels:
      app: todoapp
  endpoints:
    - port: {{ .Values.serviceMonitor.port}}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}